# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        http://amitian.github.io


# Setup
title:            Ami Tian
tagline:          'Data Analyst / Data Scientist'
description:      'a portfolio of data science projects'
url:              https://amitian.github.io
baseurl:

author:
  name:           'Ami Tian'
  url:            https://amitian.github.io

paginate:         5

# Custom vars
version:          2.1.0

github: https://github.com/amitian/

theme: jekyll-theme-minimal
