# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        http://amitian.github.io
relative_permalinks: true

# Setup
title:            Ami Tian
tagline:          'Data Analyst / Data Scientist'
description:      'a portfolio of data science projects'
url:              http://amitian.github.io
baseurl:          /amitian/

author:
  name:           'Ami Tian'
  url:            http://amitian.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde

theme: jekyll-theme-minimal